### ISSUE TITLE
Add option to not deactivate focused element

### ISSUE THREAD

**Issue by gorsash** [yiisoft/jquery-pjax#19]
There's code in jquery-pjax.js

    document.activeElement.blur();

It can be very annoying if you type something into filter input, pjax reloads result grid and filter input loses focus. Moreover in this case backspace brings you to previous page instead of erasing character.
Can you add option to not deactivate focused element? It can be called "noBlur" for instance.
And then pjax will blur element only if this option is not set:

    if (!noBlur) {
        document.activeElement.blur();
    }

**Comment by bobalazek** [comment]
+1

**Comment by SilverFire** [comment]
Fixed in the upstream
