### ISSUE TITLE
Problem with the browser Back button.

### ISSUE THREAD

**Issue by aquataller** [yiisoft/jquery-pjax#20]
Hi, I'm implementing this example: http://www.yiiframework.com/wiki/772/pjax-on-activeform-and-gridview-yii2

But instead of adding records, i´m using it to search a model via GET.
Everything behaves the way it should, exept when I use the browser back button and reach the first state without any search,  pjax is replacing the GridView with a duplicate of the search form, so I´m getting a page with two search forms and no GridView.

I've also tested it using a plain CRUD generated by Yii, and I get the same wrong behavior.

**Comment by SilverFire** [comment]
May be fixed in #21 
Could you try the dev-version, please?

**Comment by SilverFire** [comment]
@aquataller Could you check, please?

**Comment by aquataller** [comment]
Sorry, the project is already closed and I can't make any modifications or test it

**Comment by SilverFire** [comment]
Ok, thank you for the response. I'll close the issue because it really seems to be fixed in #21
