### ISSUE TITLE
Дублирование полей в GET форме

### ISSUE THREAD

**Issue by sosnovski** [yiisoft/jquery-pjax#24]
Александр, подскажите, по какой причине pjax виждет (yii2-pjax) дублирует параметры в url при сабмите get формы?

**Comment by samdark** [comment]
Как это воспроизвести?

**Comment by SilverFire** [comment]
@sosnovski проблема еще актуальна?

**Comment by SilverFire** [comment]
Я думаю, это связано с #15

**Comment by SilverFire** [comment]
Закрываю, так как скорее всего исправлено #15, нет возможности воспроизвести и автор не отвечает.
