### ISSUE TITLE
Issue with external script and PJAX

### ISSUE THREAD

**Issue by nkostadinov** [yiisoft/jquery-pjax#41]
Currently the PJAX implementation has some flaws requiring all external scripts to be loaded before using it. See https://github.com/defunkt/jquery-pjax/issues/331

I saw that you have already fixed the issue 

> Bug #23: Fixed loading of scripts in pjax containers (nkovacs, silverfire)

 :) so my question now is when will the new version 2.0.6 of yiisoft/jquery-pjax be released since it solves this problem.

**Comment by samdark** [comment]
@SilverFire is there anything preventing us from tagging new release?

**Comment by SilverFire** [comment]
No

**Comment by SilverFire** [comment]
https://github.com/yiisoft/jquery-pjax/releases/tag/v2.0.6

**Comment by SilverFire** [comment]
Released. Thank you
