### ISSUE TITLE
full page refresh after redirect

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/jquery-pjax#44]
I also have [this issue](https://github.com/yiisoft/yii2/issues/4395#issuecomment-160000534). If I use `$this->redirect` in the controller, pjax will refresh the full page.

I've looked at the new `pushRedirect` and `replaceRedirect` options. Why is there a `window.location.replace` immediately after [`pushState`](https://github.com/yiisoft/jquery-pjax/blob/v2.0.6/jquery.pjax.js#L278) and [`replaceState`](https://github.com/yiisoft/jquery-pjax/blob/v2.0.6/jquery.pjax.js#L438)? That will cause a full page refresh.

Shouldn't it be something like this:

``` js
if (pushRedirect) {
    pushState(...);
} else if (replaceRedirect && pjax.options.history) {
    replaceState(...);
} else {
    location.replace() // old code that replaced after redirect
}
```

Edit: this isn't enough, because this just changes the url in the address bar, it doesn't actually load any new content. The redirect should be allowed to happen, but [\yii\web\Response](https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L752) prevents it if checkAjax is true.

**Comment by nkovacs** [comment]
Also, you should not put replaceState into locationReplace. locationReplace is used for few other cases when pjax needs to do a full page refresh, e.g. on a version mismatch: https://github.com/yiisoft/jquery-pjax/blob/v2.0.6/jquery.pjax.js#L304. If you remove location.replace from there, you'll break that functionality.

**Comment by nkovacs** [comment]
Also, I think what `\yii\web\Response` is doing is wrong. If `checkAjax` is true, it sends out a 302 response without a Location header, but with an X-PJAX-URL header. This causes jquery ajax call to error out, and pjax to fall back to reloading the whole page using X-PJAX-URL. So it doesn't break completely, but it forces a page refresh.

The [way it's meant to be used](https://github.com/defunkt/jquery-pjax/issues/580#issuecomment-146244309) is this: The server sends out a 302 with a Location header. Jquery follows the redirect. The target page sends out the X-PJAX-URL header, so that pjax can correctly set the url in the address bar (otherwise you'd see the url that was requested, not the redirection target, because pjax cannot see the 302 response).

**Comment by manu1222** [comment]
Any update please, I also have this issue.

**Comment by manu1222** [comment]
Browser redirection is still happening even if I use redirect like below:
`return $this->redirect(array_merge(['agency/index'], $params), 302, false);` //$checkAjax = false. 

> * @param boolean $checkAjax whether to specially handle AJAX (and PJAX) requests. Defaults to true,
     * meaning if the current request is an AJAX or PJAX request, then calling this method will cause the browser
      to redirect to the given URL. 
     * If this is false, a `Location` header will be sent, which when received as
      an AJAX/PJAX response, may NOT cause browser redirection.

**Comment by dynasource** [comment]
feel free to do a PR to fix this behavior. I advise you not to wait for a solution from our side, as we are about to drop support for this library.

**Comment by nkovacs** [comment]
@manu1222 checkAjax=false is broken because it doesn't send out an X-Pjax-Url header.

I've added the following to my version of the Pjax widget, before the send here: https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L165

    if (!isset($response->headers['X-Pjax-Url'])) {
        $response->headers->set('X-Pjax-Url', Yii::$app->request->url);
    }

I also modified the Response component in my app to always have checkAjax=false, because checkAjax=true is also broken and should never have existed.

@dynasource In 2.1 or 2.0.x?
What about backwards compatibility?

**Comment by dynasource** [comment]
> What about backwards compatibility?

depends on whats need to be changed. Just adding the above code does not seem harmful.

**Comment by nkovacs** [comment]
No, I meant if you remove pjax. You can't do that in 2.0.x

**Comment by manu1222** [comment]
@nkovacs Perfect, it's working. It would be great if you can create PR for the same. When I passed checkAjax = false inside controller's redirect(), it didn't work but when I modified Response.php, it worked. Yeah It's broken. The point is we need checkAjax  to be set dynamically because there may be some places we need to redirect page after pjax request. Everything looks perfect. PR would be a great thing. I hope so.

**Comment by manu1222** [comment]
If you are dropping support for this library. It's like we can't upgrade to latest versions of Yii2 in future. It will break the existing pjax. So should I prefer using Pjax via Yii2 or it would be a great idea to use it directly? @dynasource

**Comment by dynasource** [comment]
It is unknown when we are dropping support it, but for 2.0.x you are safe. Please understand that this is an external library and that we don't want to be dependant of it anymore. If it works, it works great. But if it doesnt work, you are pulling your hairs out to find the issue. We don't want that anymore in the future. Perhabs we will developer our own library.

**Comment by samdark** [comment]
It won't be dropped in 2.0.x for sure.

**Comment by samdark** [comment]
Solved by https://github.com/yiisoft/yii2/pull/13694
