### ISSUE TITLE
"history" option does not count by all code

### ISSUE THREAD

**Issue by li-ar** [yiisoft/jquery-pjax#54]
Hello!
There is code line in pjax lib (https://github.com/yiisoft/jquery-pjax/blob/master/jquery.pjax.js#L387):
`window.history.replaceState(pjax.state, document.title)`
And it does not count "history" options. So when I set it to false - this line runs anyway. Looks like a small bug to me, am I right or missed something?
P.S. commit version is aeb1a2d273fc70342682648fa2239d0aec3e86b6

**Comment by SilverFire** [comment]
Thank you
