### ISSUE TITLE
New version of pjax

### ISSUE THREAD

**Issue by armpogart** [yiisoft/jquery-pjax#55]
Original jquery-pjax was updated recently to new version with some minor backward incompatibilities, will you accept pull request to this repo with those changes?

**Comment by samdark** [comment]
Depends on what these incompatibilities are and if they'll break existing projects. Also, we have our own changes to the code.

**Comment by armpogart** [comment]
First full CHANGELOG from the latest merge from upstream to this repo (by versions):

**1.9.6**
- Change internal cache struct to fix restoring mixed containers.
- Avoid tackling on extra # on URLs in Safari.
- Fix stripping internal query params to avoid touching & and ? in components other than query string.

**2.0.0**
- **This release brings jQuery 3.x compatibility.**
- The value of container parameter to pjax functions should be a string selector, and not a jQuery object anymore. (backwards incompatible)
- The value of container parameter cannot be a DOM node with an ID anymore. (backwards incompatible)
- The call signature $("#main").pjax("a") is not supported anymore because the container selector #main cannot be inferred from the context of the $.fn.pjax() call. To fix this, pass the container selector explicitly: $("#main").pjax("a", "#main") (backwards incompatible)

**2.0.1** (I suppose some of these changes can also be backwards incompatible with the old version)
- Fix blurring current active element within pjax container
- Remove extra & after stripping internal query params
- Handle documents with no or empty <head> tag
- Fix npm warnings about package.json
- Add eslint to project

I haven't checked which backwards incompatible changes would also be backwards incompatible here, as this fork is mainly used through `Yii::pjax`` wrapper which can overcome some backwards incompatibilities I guess. But the jQuery 3.x compatibility is very important in my opinion and original repo is again under constant development now (more or less), so it would be helpful to incorporate upstream changes.

May I try to prepare PR? (отталкиваясь из того, что не все изменения сломают эту версию, так как она не используется отдельно, а через Yii, и можно сохранить совместимость через PHP код)

**Comment by samdark** [comment]
Yes, you can prepare a pull request but then you should be careful since we have our own changes in the code.

**Comment by samdark** [comment]
https://github.com/yiisoft/jquery-pjax/issues/59

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/jquery-pjax/commit/047a0b08c9eb4f23b9dfb3a5bdabdfd0d52e5917
