### ISSUE TITLE
Can not work with jQuery3.x

### ISSUE THREAD

**Issue by a761208** [yiisoft/jquery-pjax#57]
Uncaught TypeError: Cannot read property 'push' of undefined
    at jquery.pjax.js:981
    at jquery.pjax.js:991

L981:`$.event.props.push('state')`

Fixed with these:
```javascript
if ( $.event.props && $.inArray('state', $.event.props) < 0 ) {
  $.event.props.push('state');
} else if ( ! ('state' in $.Event.prototype) ) {
  $.event.addProp('state');
}
```

**Comment by cebe** [comment]
could you please make a pull request from your fix?
