### ISSUE TITLE
Need update package version on npmjs.com

### ISSUE THREAD

**Issue by webdevsega** [yiisoft/jquery-pjax#60]
On npmjs.com the latest version is 2.0.6

**Comment by samdark** [comment]
@SilverFire ?

**Comment by samdark** [comment]
I'll handle it.

**Comment by schmunk42** [comment]
@webdevsega Which package do you mean? https://www.npmjs.com/package/pjax is 2.0.4

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
yii2-pjax.

**Comment by schmunk42** [comment]
@SilverFire @hiqsol How long is the interval for asset-packagist to fetch updates automatically?

@samdark Is is basically a solution in such a case to click the **Fetch** button on asset-packagist for such a package?

**Comment by samdark** [comment]
It's not connected to asset packagist in any way, it's about npm. asset-packagist uses bower.

**Comment by schmunk42** [comment]
Sorry for the confusion, I first thought it's about `pjax` and there were two versions missing.

> asset-packagist uses bower.

asset-packagist is able to use bower and npm ;) https://asset-packagist.org/package/search?query=yii2-pjax&platform=bower%2Cnpm
