### ISSUE TITLE
Event "Complite" calling before "Send" when async: false

### ISSUE THREAD

**Issue by reverse-cat** [yiisoft/jquery-pjax#66]
maybe it's okay but still it's odd and i cant use events step by step.
for example i try block screen before pjax was finished but it going wrong.
[test controller & view.zip](https://github.com/yiisoft/jquery-pjax/files/1736060/test.controller.view.zip)

**Comment by samdark** [comment]
Fixed with https://github.com/yiisoft/jquery-pjax/pull/72
